# Generated by Django 3.1.1 on 2021-07-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('address', models.CharField(max_length=254)),
                ('phone_number', models.IntegerField(null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=50)),
                ('center_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Catgry',
            fields=[
                ('issue_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('career_descrptn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('issue_description', models.TextField(max_length=150)),
                ('urgent', models.CharField(max_length=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('center_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supportapp.center')),
                ('cluster_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supportapp.cluster')),
                ('issue_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportapp.issue_catgry')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='cluster_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportapp.cluster'),
        ),
        migrations.AddField(
            model_name='coachuser',
            name='center_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supportapp.center'),
        ),
        migrations.AddField(
            model_name='coachuser',
            name='cluster_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supportapp.cluster'),
        ),
        migrations.AddField(
            model_name='coachuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='coachuser',
            name='staff_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supportapp.staff'),
        ),
        migrations.AddField(
            model_name='coachuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
