# Generated by Django 3.1.1 on 2021-07-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0002_auto_20210723_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='reported_to',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
